// Felt Dashboard Application
// Generated by Felt GIS Workbench

import { Felt } from "https://esm.run/@feltmaps/js-sdk";

let felt;
let currentFilters = {};

async function initializeMap() {
    try {
        // Embed Felt map
        felt = await Felt.embed(
            document.getElementById('map'),
            '3B9BEm9BYAQ6qINpaPYOW82B',
            {
                uiControls: {
                    showZoomControls: true,
                    showLegend: true,
                    showSearch: false,
                    showShare: true
                }
            }
        );

        console.log('Felt map loaded successfully');

        // Update stats if using dashboard layout
        await updateStats();

        // Setup event listeners
        setupEventListeners();

        

        // Listen to map interactions
        felt.onPointerMove({
            handler: (event) => handlePointerMove(event)
        });

        felt.onPointerClick({
            handler: (event) => handlePointerClick(event)
        });

    } catch (error) {
        console.error('Failed to initialize map:', error);
        showError('Failed to load map. Please check your connection.');
    }
}



async function updateStats() {
    // Update stat cards if they exist (dashboard layout)
    try {
        const layers = await felt.getLayers();

        if (layers && layers.length > 0) {
            // Get the first data layer (skip basemap)
            const dataLayer = layers.find(l => l.type !== 'basemap');

            if (dataLayer) {
                // Update feature count
                const featureCountEl = document.getElementById('stat-features');
                if (featureCountEl && dataLayer.featureCount !== undefined) {
                    featureCountEl.textContent = dataLayer.featureCount.toLocaleString();
                }

                // Update data type
                const dataTypeEl = document.getElementById('stat-type');
                if (dataTypeEl && dataLayer.geometryType) {
                    dataTypeEl.textContent = dataLayer.geometryType;
                }

                // Update last updated time
                const updatedEl = document.getElementById('stat-updated');
                if (updatedEl) {
                    const now = new Date();
                    updatedEl.textContent = now.toLocaleTimeString();
                }

                console.log('Stats updated:', {
                    features: dataLayer.featureCount,
                    type: dataLayer.geometryType
                });
            }
        }
    } catch (error) {
        console.error('Error updating stats:', error);
        // Stats update is non-critical, don't show error to user
    }
}

function handlePointerMove(event) {
    // Handle mouse movement over map
    if (event.features && event.features.length > 0) {
        // Show feature info on hover
        const feature = event.features[0];
        updateFeatureInfo(feature);
    }
}

function handlePointerClick(event) {
    // Handle click on map features
    if (event.features && event.features.length > 0) {
        const feature = event.features[0];
        console.log('Clicked feature:', feature);
        showFeatureDetails(feature);
    }
}

function updateFeatureInfo(feature) {
    const infoDiv = document.getElementById('feature-info');
    if (infoDiv) {
        infoDiv.innerHTML = `
            <div class="feature-preview">
                <h3>Hover Info</h3>
                <p>${JSON.stringify(feature.properties, null, 2)}</p>
            </div>
        `;
    }
}

function showFeatureDetails(feature) {
    const infoDiv = document.getElementById('feature-info');
    if (infoDiv) {
        infoDiv.innerHTML = `
            <div class="feature-details">
                <h3>Selected Feature</h3>
                <pre>${JSON.stringify(feature.properties, null, 2)}</pre>
            </div>
        `;
    }
}

function setupEventListeners() {
    // Add any additional event listeners here
    console.log('Event listeners setup complete');
}

function showError(message) {
    const mapContainer = document.getElementById('map');
    mapContainer.innerHTML = `
        <div class="error-message">
            <h2>⚠️ Error</h2>
            <p>${message}</p>
        </div>
    `;
}

// Initialize when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    initializeMap();
});